baseURL = "https://herr-felix.dev/"
languageCode = "en-CA"
title = "Herr Felix's internet ranch"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4
